### ISSUE TITLE
Duplicate 'otherFeatures' entry in London Case 3 (ID c643bff833aaa9a47e3421a8c8f35445)

### ISSUE THREAD

**Issue by neopostmodern** [babylonhealth/itu_who_2019_symptom_assessment_mmv_benchmark#18]
In the London Model Case 3 "Vomiting" appears twice, with the same ID
```
        {
          "state": "present",
          "name": "Vomiting",
          "id": "c643bff833aaa9a47e3421a8c8f35445"
        },
```

Simply removing these lines from `data/doctor_cases/london_model/cases.json` is not enough, it has to be also removed from `evaluator/data/london_model2019_cases_v1/cases.json` but the latter is a non-tracked file and I wasn't able to figure out how the data gets copied/generated there. Simply re-running `run_all.py` was not enough.

**Comment by perov-babylon** [comment]
@neopostmodern, thank you. I have fixed the original spreadsheet: https://docs.google.com/spreadsheets/d/111D40yoJqvvHZEYI8RNSnemGf0abC9hQjQ7crFzNrdk/edit#gid=1175944267 and updated the repo: https://github.com/babylonhealth/itu_who_2019_symptom_assessment_mmv_benchmark/pull/24

The cases are currently copied here: https://github.com/babylonhealth/itu_who_2019_symptom_assessment_mmv_benchmark/blob/master/evaluator/api.py#L83 (that should be improved/refactored).

**Comment by perov-babylon** [comment]
Could you tell, please, is it okay to close the issue?

**Comment by neopostmodern** [comment]
Yes, works fine now!
